// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TUS DATOS REALES (Ya pegados):
const SUPABASE_URL = "https://ggvrcfjnrtohiahmfofw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdndnJjZmpucnRvaGlhaG1mb2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MzU3NjAsImV4cCI6MjA4NDQxMTc2MH0.9ftzbRvEDDLHGk4l8xJLrSDxf9_g7RQMjJ0pABnizWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
